In [2]:
import numpy as np

In [8]:
#ayuda para saber que tiene numpy
np.lookfor("EDO")
np.lookfor("solve")

Search results for 'edo'
------------------------
numpy.std
    Compute the standard deviation along the specified axis.
numpy.var
    Compute the variance along the specified axis.
numpy.poly
    Find the coefficients of a polynomial with the given sequence of roots.
numpy.nanstd
    Compute the standard deviation along the specified axis, while
numpy.nanvar
    Compute the variance along the specified axis, while ignoring NaNs.
numpy.ma.var
    Compute the variance along the specified axis.
Search results for 'solve'
--------------------------
numpy.linalg.solve
    Solve a linear matrix equation, or system of linear scalar equations.
numpy.linalg.lstsq
    Return the least-squares solution to a linear matrix equation.
numpy.linalg.tensorsolve
    Solve the tensor equation ``a x = b`` for x.
numpy.nditer.close
    close()
numpy.shares_memory
    Determine if two arrays share memory
numpy.linalg.pinv
    Compute the (Moore-Penrose) pseudo-inverse of a matrix.
numpy.linalg.cholesky
   

In [11]:
#constantes
print(np.pi, np.e)

3.141592653589793 2.718281828459045


In [18]:
# rango de 0 a 10 y que sea 21 elementos

print(np.linspace(0,10,21))
print(len(np.linspace(0,10,21)), "elementos del array")

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]
21 elementos del array


In [25]:
#nota el ultimo parametro no se incluye en el rango
print(np.arange(0,11))
#un rango de 0 a 11 saltando de 3 en 3
print(np.arange(0,11,3))

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 3 6 9]


In [29]:
# escala logaritmica
np.logspace(0,3,4)

array([   1.,   10.,  100., 1000.])

In [33]:
#Comenzaremos por crear un array 1d con los valores (1,2,3,4,5,6,7,8,9) usando np.arange().
#Luego le daremos forma de array 2d. con np.reshape(array, (dim0, dim1))
a = np.arange(1,10)
M = np.reshape(a, [3,3])
print(M)

#otra forma
N = a.reshape([3,3])
print("\n\n",N)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
#indexaccion de arrays
m1 = np.array([
    [1,2,3],
    [4,5,6]]
        )
# la clasica
print(m1[0][0],"\n\n")
# hay que repetir una otra vez que el rango  es  n:m => n,n+1,....m-1 hasta
print("matriz original\n",m1)
print("\nobtengo una submatriz \n",m1[0:2,1:3])
print("\nmatriz identidad de int y no de float\n",np.identity(4).astype(int))
print("\nfilas y columnas tuplas: ",np.identity(3).shape,"\n",np.identity(3))

1 


matriz original
 [[1 2 3]
 [4 5 6]]

obtengo una submatriz 
 [[2 3]
 [5 6]]

matriz identidad de int y no de float
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

filas y columnas tuplas:  (3, 3) 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [65]:
a = np.arange(6).reshape(2,3)
print(np.sqrt(a))
print("\n\nla raiz de numero complejos\n",np.arange(-3,3).astype(complex).reshape(2,3),
      "\n\nraiz\n",np.sqrt(np.arange(-3,3).astype(complex).reshape(2,3)))

[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]]


la raiz de numero complejos
 [[-3.+0.j -2.+0.j -1.+0.j]
 [ 0.+0.j  1.+0.j  2.+0.j]] 

raiz
 [[0.        +1.73205081j 0.        +1.41421356j 0.        +1.j        ]
 [0.        +0.j         1.        +0.j         1.41421356+0.j        ]]


In [74]:
#comparaciones
m2 = np.arange(6).astype(float)
m3 = np.ones(6)
print("\nm2\n",m2)
print("\nm3\n",m3)
print("\n m2 == m3 \n",np.isclose(m2,m3,rtol=1e-2))#para la igualdad de los .flotante (float) le doy el rango de tolerancia
print("\nalguno es verdaro\n",np.any(m2<m3))
print("\ntodos son verdaros\n",np.all(m2<m3))


m2
 [0. 1. 2. 3. 4. 5.]

m3
 [1. 1. 1. 1. 1. 1.]

 m2 == m3 
 [False  True False False False False]

alguno es verdaro
 True

todos son verdaros
 False
